### ISSUE TITLE
No effect on rules with only `object-position`

### ISSUE THREAD

**Issue by jeanfredrik** [ronik-design/postcss-object-fit-images#17]
This plugin doesn’t seem to handle the case when a CSS rule contains a `object-position` declaration but no `object-fit` declaration. Example:

```css
.object-contain-top {
  object-fit: contain;
  object-position: top;
}
.object-top {
  object-position: top;
}
```
becomes
```css
.object-contain-top {
  object-fit: contain;
  object-position: top;
  font-family: 'object-fit:contain;object-position:top';
}
.object-top {
  object-position: top;
  /* No font-family here */
}
```
The reason I need this is that I'm using Tailwindcss.
